### PR TITLE
Find a little mistake in `Makefile`

### PR DESCRIPTION
**Pull request by GiantZwlin**
the `mod` should be `dep`  according to the `CONTRIBUTING.md`

### CODE REVIEW

**Comment by saltbo** [comment]
Thanks for your PR, can you update the CONTRIBUTING.md?

**Comment by GiantZwlin** [comment]
OK, Did you mean keep the `Makefile` unchanged and fixd the `CONTRIBUTING.md`?

**Comment by saltbo** [comment]
Yes, and you should reset your old commits to keep one commit only

**Comment by saltbo** [comment]
No need to re-fork. 

1. `git reset --soft HEAD~5`
2. `git commit ''`
3. `git push -f origin master`

**Comment by GiantZwlin** [comment]
Sorry,I am a student and do not really know how to use git, and I also think the commits are to much, I'll learn to reset them.

**Comment by GiantZwlin** [comment]
> No need to re-fork.
> 
> 1. `git reset --soft HEAD~5`
> 2. `git commit ''`
> 3. `git push -f origin master`

but I had delete the old fork, what should I do?

**Comment by saltbo** [comment]
Unfortunately, in this case you can only resubmit the PR

**Pull request closed without merging**
